### ISSUE TITLE
Hexlet

### ISSUE THREAD

**Issue by luckyuturov** [Hexlet/ru-test-assignments#118]

**Comment by ashikov** [comment]
Приветствую, @luckyuturov! Вы нашли какую-то проблему или же есть предложение? =) Если нет, и issue был создан по ошибке, то я его закрою.

**Comment by luckyuturov** [comment]
Здравствуйте. Прошу прощения, случайно вышло)

**Comment by ashikov** [comment]
Ничего страшного, бывает) Пишите, если что
