### ISSUE TITLE
Тестовое задание Aviasales (frontend) (JS/TS, React)

### ISSUE THREAD

**Issue by kaamosdao** [Hexlet/ru-test-assignments#122]
Добрый день!
По данному тестовому заданию: [Тестовое задание Aviasales (frontend) (JS/TS, React)](https://github.com/KosyanMedia/test-tasks/tree/master/aviasales_frontend).
Запросы на сервер возвращают ошибку, похоже он не работает.
Это тестовое задание еще актуально?

**Comment by fey** [comment]
Можете прислать ПР с удалением тестового.
