### ISSUE TITLE
Не открываются некоторые сайты

### ISSUE THREAD

**Issue by AABur** [Hexlet/ru-test-assignments#132]
У меня некоторые сайты компаний не открываются. Возможно проблемы доступа связаны с тем что  я проверяю из Европы. Проверьте пожалуйста.

~~https://au.ru/~~
~~https://drupaljedi.com/~~
http://digitaldali.pro/
~~https://funbox.ru/~~
https://gojuno.com/
~~https://www.pokerstars.com/~~
~~https://infomatika.ru/~~

**Comment by julmedvedeva** [comment]
у меня открылись: 

https://au.ru/
https://funbox.ru/
https://infomatika.ru/

**Comment by ajib6ept** [comment]
У меня также открылся

https://www.pokerstars.com/ (переадресация на https://www.pokerstars.fr/)

**Comment by ashikov** [comment]
Работает:
* https://drupaljedi.com/

**Comment by EvilLogitech** [comment]
Не открывается тестовое задание для Apsolutions - "Тестовое задание для стажера (Python)"

**Comment by David-Roklem** [comment]
> Не открывается тестовое задание для Apsolutions - "Тестовое задание для стажера (Pyth

> Не открывается тестовое задание для Apsolutions - "Тестовое задание для стажера (Python)"

аналогично
