### ISSUE TITLE
проверка на битые ссылки

### ISSUE THREAD

**Issue by MilaNick** [Hexlet/ru-test-assignments#159]
- https://github.com/appbooster/test-assignments/blob/master/tasks/html-css.md макет в figme не найден, написано доступен без инвайтов 
- https://github.com/avito-tech/safedeal-frontend-trainee  ​Дизайн можно найти тут и ответы на вопросы по заданию можно найти тут - обе ссылки нерабочие
- https://github.com/devjsru/react_test  макет в figme не найден
- https://github.com/fs/test-tasks/tree/master/front-end#%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2 макет в figme не найден, sketch-файл не найден
- https://github.com/fs/test-tasks/tree/master/unity  Требуется реализовать перечисленные задачи над существующим тестовым проектом - ссылка нерабочая
- https://github.com/appKODE/test2019 ошибка 500
- https://github.com/appKODE/2018-internship-backend ошибка, изображение не найдено

**Comment by ashikov** [comment]
Оу. Может быть закинете пулреквест с правками? Будет круто. :)

**Comment by MilaNick** [comment]
могу, но не получается сделать pr, кнопка неактивна

**Comment by MilaNick** [comment]
да, сделаю
