### ISSUE TITLE
Ожидают добавления

### ISSUE THREAD

**Issue by mokevnin** [Hexlet/ru-test-assignments#16]
https://github.com/evrone/easy_test
https://github.com/EvercodeLab/php-test-assignment
https://github.com/hhru/frontend-test
https://gist.github.com/shiroginne/2cd4ade25d7c81f28798
https://github.com/nikolaychernov/StudentDatabase
https://github.com/eniqen/Java_School_Tasks
https://github.com/sorovlad/kontur-test-work
https://github.com/bozaro/tech-db-forum
https://github.com/KosyanMedia/test-tasks/tree/master/aviasales
https://github.com/gojuno/test_tasks

**Comment by adsurov** [comment]
Еще
https://github.com/devjsru/react_test
