### ISSUE TITLE
Add test assignments for analysts from Pavel Buchtik's list

### ISSUE THREAD

**Issue by fey** [Hexlet/ru-test-assignments#206]
I uploaded test cases for analysts to our google disk https://drive.google.com/drive/folders/1Hu_MzR8sV5k8A2MBrOZXS9QV1unoK_e9 It is necessary to add test cases to our repository. I recommend adding one or more of them in order to avoid confusion. 64 companies in total.
- [ ] https://drive.google.com/open?id=1X2s0oLF1Br0WqT4f6xpj_x-nbm-ONcb8&usp=drive_copy
- [ ] https://drive.google.com/open?id=1wioL44aMEbdIDg1rvglKx1IOFPyIfakJ&usp=drive_copy
- [ ] https://drive.google.com/open?id=1FDHErQLGvPoJKECmRqijpwuVifnTaw8x&usp=drive_copy
- [ ] https://drive.google.com/open?id=1CgmQ_OEW2GrOrDPZEJUIRCLVL0JAkdRC&usp=drive_copy
- [ ] https://drive.google.com/open?id=1pPuyOvBGgqosSfEvy3KCuv1FO1vED1cl&usp=drive_copy
- [ ] https://drive.google.com/open?id=1sYeVs3_fY5vamQjgZ3KRvxQSeEkzr0gJ&usp=drive_copy
- [ ] https://drive.google.com/open?id=1GEBYxCwKh_DdwnK_p-dsxuaC-gj_eVgM&usp=drive_copy
- [ ] https://drive.google.com/open?id=1EMRCcMT852e-rAxliXn-3eihjcS2SnP-&usp=drive_copy
- [ ] https://drive.google.com/open?id=10OtwaqT0Hntjv8ClW2SrdBL0QKTs3TPX&usp=drive_copy
- [ ] https://drive.google.com/open?id=1-XyMfD-7co6rO9mXqpVL5c0JDwL2GpzN&usp=drive_copy
- [ ] https://drive.google.com/open?id=124G-etb0MME9VIQYJD-DHKd-VgQGbZ2l&usp=drive_copy
- [ ] https://drive.google.com/open?id=1aeFVwgsMCosQUBlne_WqochPwFJUXGtR&usp=drive_copy
- [ ] https://drive.google.com/open?id=1USRtuNu-BKAvQd6_AVDhIM22mddng86E&usp=drive_copy
- [ ] https://drive.google.com/open?id=1Xbhp0ZDoHfwNQiP1aH2TXryod_qdEvrx&usp=drive_copy
- [ ] https://drive.google.com/open?id=1e_OMZjTO3WA3s8Em7Df4rpjrllqZNmhP&usp=drive_copy
- [ ] https://drive.google.com/open?id=16tRtN53FZ_FT3__Ay1biP3nb-CrkZ92I&usp=drive_copy
- [ ] https://drive.google.com/open?id=1CiYVO0rTRqaxBTzuOXHAN180FR89ODns&usp=drive_copy
- [ ] https://drive.google.com/open?id=1hJ6E-YAtObNP0DtZRH2814WBcBEb0aHo&usp=drive_copy
- [ ] https://drive.google.com/open?id=1wYCaprk3AwfTdwqFB-ESDbz9hZRgRDKG&usp=drive_copy
- [ ] https://drive.google.com/open?id=1q0OGFTUI58Gbar-rq3Dp4Zr9XuvqDkbs&usp=drive_copy
- [ ] https://drive.google.com/open?id=1w5xhj_ApzUJX-xf-cIBCYgGvy2t3PPML&usp=drive_copy
- [ ] https://drive.google.com/open?id=1LUqYcKfwSSVtgoibiS4ngUHtg2o3axs1&usp=drive_copy
- [ ] https://drive.google.com/open?id=1lZiv0cIUaPL1lV9Eg1T-tKvJJQ2u6nt5&usp=drive_copy
- [ ] https://drive.google.com/open?id=1UCuCV4i5hSEJkI6W6AKsYPKBy6Qpxcj9&usp=drive_copy
- [ ] https://drive.google.com/open?id=1ThbDAnbCrQ21jqk7bF2l-wCpWlUvVT7N&usp=drive_copy
- [ ] https://drive.google.com/open?id=1uCFwwQnihShdtwbwCLU47oiJanFa50HA&usp=drive_copy
- [ ] https://drive.google.com/open?id=1vJxxik-PknPc7Gx-aSAP91Ll9eEZnAAo&usp=drive_copy
- [ ] https://drive.google.com/open?id=1W6ALYVV6jNhGzv3us8sKOuCvFY5ofD41&usp=drive_copy
- [ ] https://drive.google.com/open?id=1a8RmVxSvqoJMUlajVxLTp5-WnSkG3MTN&usp=drive_copy
- [ ] https://drive.google.com/open?id=1vhEmlyL3HxY9HMybTXll6GGc7FPQ730h&usp=drive_copy
- [ ] https://drive.google.com/open?id=1T27FerfXXgNj033iqDumKjpbuWFSnZOl&usp=drive_copy
- [ ] https://drive.google.com/open?id=1SlMKX5jFnax5jyWmGQq6h5KWe9lSoQvC&usp=drive_copy
- [ ] https://drive.google.com/open?id=1uE_AM2IFSxP33393KYrNE8RQqoTREfvU&usp=drive_copy
- [ ] https://drive.google.com/open?id=12Dk5mj04RR7ThE_ONd0CivF4r8ok2uqG&usp=drive_copy
- [ ] https://drive.google.com/open?id=1FS0GtB_DxK4ZgrI8s6zMSPCYiDhtETNY&usp=drive_copy
- [ ] https://drive.google.com/open?id=1PHzuS3TWdLJBthV35Ra3q1oF9RzEuZ2u&usp=drive_copy
- [ ] https://drive.google.com/open?id=1vnIVQFrnPSXDD-YAiHfu1uc7se5x6ZMu&usp=drive_copy
- [ ] https://drive.google.com/open?id=1IjyT-jC8VHKCkru2Wuq-0fCDZnMNtQBO&usp=drive_copy
- [ ] https://drive.google.com/open?id=1Y8qnmQunaCpIf-jzud9f-jnB_t74EVaC&usp=drive_copy
- [ ] https://drive.google.com/open?id=17MJaFDH5tj9oO8uBUTu33QTI7cJ64AWx&usp=drive_copy
- [ ] https://drive.google.com/open?id=1-8SRmxsZiezLvVtINR_VPgm5_908lpN3&usp=drive_copy
- [ ] https://drive.google.com/open?id=1wZ9S0QHaCNvNrVNxgSYxptBSaeVUX74U&usp=drive_copy
- [ ] https://drive.google.com/open?id=1t1YPyDecBiLLhLE6fwMwfBLgS7583x2i&usp=drive_copy
- [ ] https://drive.google.com/open?id=1pF55pb-o9pyIt-oiPsMAfPJeoojItvC4&usp=drive_copy
- [ ] https://drive.google.com/open?id=1HNEZgaccltEHCEbC-fiiMuHzur5jFPxh&usp=drive_copy
- [ ] https://drive.google.com/open?id=1aqfEfITwbt3aqzJ15Et7XD6uwwFXcy7M&usp=drive_copy
- [ ] https://drive.google.com/open?id=113sKiIAF3YMCcah1VSojHiW3YIRYILqe&usp=drive_copy
- [ ] https://drive.google.com/open?id=1JkF9GW-El59XVcdpR-g6UfYO8sKwIssw&usp=drive_copy
- [ ] https://drive.google.com/open?id=11HFrOt2QF3h1swIe8lwuzhVjgwM0ksgT&usp=drive_copy
- [ ] https://drive.google.com/open?id=18yjaMxWI9qpPa-9kTojYuNVcCj6iG8Pd&usp=drive_copy
- [ ] https://drive.google.com/open?id=1psIKzvNN3-vtvKHVi8SbCrg-jngtWgaS&usp=drive_copy
- [ ] https://drive.google.com/open?id=1ytwdhsT11IxXGU7Jav9WhV2GqVBo2PJH&usp=drive_copy
- [ ] https://drive.google.com/open?id=17VMzVwew-SkXdsbZXxaeDDGEUQXYhKxn&usp=drive_copy
- [ ] https://drive.google.com/open?id=10oIsaqsZoOK49QO3uxw_8UuxaXfI6tl0&usp=drive_copy
- [ ] https://drive.google.com/open?id=1ziQs9oEab9eENnuArVTVVZWLsljKDQqO&usp=drive_copy
- [ ] https://drive.google.com/open?id=1R_RgzWhcAb4l1XoMCHzuYM-JdH_PbWDn&usp=drive_copy
- [ ] https://drive.google.com/open?id=1G0VwPL-6T0ThPdLstnZK07dy1q2Mgv2T&usp=drive_copy
- [ ] https://drive.google.com/open?id=15O4odYKqRpmXSQtLgD0fbvjshIa1_TWX&usp=drive_copy
- [ ] https://drive.google.com/open?id=1JTMqKy8Kgmkh08vAW3wx8NcPfdyqXWuV&usp=drive_copy
- [ ] https://drive.google.com/open?id=1wNb27gq4JxrbSFBSkFCcrnb8Bjhs8WYM&usp=drive_copy
- [ ] https://drive.google.com/open?id=1s4h4K29JEDYXIZXtIAmMjZbp9PHeV5ic&usp=drive_copy
- [ ] https://drive.google.com/open?id=1cBUI7Qsed_7wp-yYOxBd3NseVZZ5CEEi&usp=drive_copy
- [ ] https://drive.google.com/open?id=19pwYCnUdS2tkiekHYKzpRIqCDgYUdqli&usp=drive_copy
- [ ] https://drive.google.com/open?id=1Om9a_KAL4GrZKsRvFlqhsfryjwrPYWZW&usp=drive_copy

**Comment by RossJeanCarter** [comment]
взял в работу

**Comment by Vkube** [comment]
@fey @RossJeanCarter, приветствую  давайте как-то  пронумеруем какие ссылки уже добавлены, чтобы закрыть все задачи. Галочками можно отметить ссылки, которые уже добавлены?

**Comment by fey** [comment]
ох, отметить можно да. Если шли о порядку - с этим проще. Если нет то.. новость печальная :D

**Comment by sergiozeppo** [comment]
@fey @Vkube 
I double-checked, @RossJeanCarter has done all the work, tasks are closed, PRs are merged. It's ok and safe to close the issue.
