### ISSUE TITLE
Репозиторий тестового задания для Byndyusoft более не существует

### ISSUE THREAD

**Issue by sergeloie** [Hexlet/ru-test-assignments#212]
https://github.com/mondayish/SimpleConsoleCalculator/blob/master/README.md
да и вообще https://github.com/mondayish больше нет

**Comment by fey** [comment]
@sergeloie пришлете ПР с удалением этого тестового?

**Comment by sergeloie** [comment]
> @sergeloie пришлете ПР с удалением этого тестового?

Да, сейчас попробую

**Comment by sergeloie** [comment]
@fey 
https://github.com/Hexlet/ru-test-assignments/pull/213
