### ISSUE TITLE
Сгруппировать задания по направлениям

### ISSUE THREAD

**Issue by fey** [Hexlet/ru-test-assignments#219]
Для удобства работы с документом нужно сгруппировать тестовые задания по направлениям и положить это дело в теги с раскрывающимися списками. Несколько направлений для примеров я добавил, нужно туда перенести, плюс добавить новые направления.

Таким образом пользователь тестировщик/аналитик/фронтендер на React сможет сразу увидеть интересные ему тестовые.

**Comment by DmitryFedoreev** [comment]
Беру

**Comment by DmitryFedoreev** [comment]
@fey задания группировать по языкам программирования или по направлениям типо Backend. Подскажи как правильнее сделать, потому что например у аналитика написано Python и у Backend Python.

Исходя из описания я понял так:

Python
- Backend разработчик
- Аналитик данных
- Продуктовый аналитик

**Comment by fey** [comment]
@DmitryFedoreev давайте разделять прям о направлениям, т.е. если то будет аналитика данных то будет Аналитик данных, если это прораммирование на питоне - то Python-разработчик. 
Для аналитиков данных пока не будем делать разделение (продуктовый/аналитик данных). - у нас же немного вакасний по этому направлению?

Как примерно может быть

* Java
* Python
* PHP
* Верстка
* Frontend (React)
* Frontend (Vuejs)
* Аналитик данных
* Android-разработка
* Ручное тестирование
* Автоматическое тестирование на JS

Т.е. тут направления будут профессиями, а что там внутри - не так важно. Если что-то прям общее, например "напишите бекенд на любом языке", то можно выделить в отдельную категорию да, типа "Бекенд"

**Comment by DmitryFedoreev** [comment]
Слушай а как быть с заданиями которые например требуют и Python и Go
Вставлять и туда и туда ?

**Comment by DmitryFedoreev** [comment]
Я не успеваю сори, постараюсь сделать в течении след недели)

**Comment by HelenOne** [comment]
@DmitryFedoreev привет! А что за задание и с Python и с Go? Думаю там нужно смотреть по смыслу, возможно выделить в отдельное направление

**Comment by DmitryFedoreev** [comment]
Там бэк

**Comment by DmitryFedoreev** [comment]
@fey @HelenOne Я добавил большинство по пунктам, но:
Как быть с такими вот тестовыми - Fraud Analyst / стажёра в команду VAS. Куда их добавлять? Pull recuest пока не создаю гляньте вот тут - https://github.com/DmitryFedoreev/ru-test-assignments

**Comment by HelenOne** [comment]
Задание для стажёра в команду VAS в папку просто фронтенд, а Fraud Analyst в аналитику данных
