### ISSUE TITLE
Тестовые задания для PHP разработчиков 

### ISSUE THREAD

**Issue by aletoropov** [Hexlet/ru-test-assignments#221]
Пропали задания на позиции PHP разработчиков. 
Хотелось бы, что бы добавили.

**Comment by fey** [comment]
@aletoropov Did  lose some specific tasks or all of them? Now we have divided the tasks by areas.

**Comment by sergiozeppo** [comment]
> Пропали задания на позиции PHP разработчиков. Хотелось бы, что бы добавили.

I think this issue should be closed. 
PHP test assginments is located under PHP section. 
![image](https://github.com/user-attachments/assets/23dd979b-c023-43d4-a54b-484bee685cf4)
