### ISSUE TITLE
separate Go into a separate category and move the Manual QA category next to Automation QA

### ISSUE THREAD

**Issue by HelenOne** [Hexlet/ru-test-assignments#225]

**Comment by niyatanya** [comment]
1) "separate Go into a separate category"
Should I move to a special Go category tests with Go and a range of other languages (marked in yellow)?
![image](https://github.com/user-attachments/assets/f79b68bf-2837-45a6-9e94-7a47d417236b)


2) "move the Manual QA category next to Automation QA" - am I understanding this part of the task right?
![image](https://github.com/user-attachments/assets/4e3bed94-4524-4cd5-9717-38c5212220ec)

**Comment by HelenOne** [comment]
1. You should move to a separate category only those tasks that do not mention other languages (PHP, Python). Tasks mentioning MySQL and Docker but not different language must also be moved 
2. Yes, that's right

**Comment by niyatanya** [comment]
Noted! I will be happy to take this issue. My personal deadline: this week (4.08 evening).

**Comment by niyatanya** [comment]
@HelenOne I finished. Kindly have a look!

I also noticed some tests from avito.tech were duplicated, even within one section. For example, test with link `https://github.com/avito-tech/auto-backend-trainee-assignment` mentioned 4 times in total, 3 times in Backend section.

![image](https://github.com/user-attachments/assets/78ee5ac3-c88e-41ef-896f-af2348a6a271)

![image](https://github.com/user-attachments/assets/37ed346d-0445-493b-8b77-cf87aac54379)

![image](https://github.com/user-attachments/assets/36f265a7-5bee-4b8a-b8fc-31a48ac97563)

I deleted duplicates which were in the scope of this issue (in Go section, Manual QA section, some in Backend section). However some other duplicates left. I can clean them if you need me to.

**Comment by HelenOne** [comment]
Great! Now we can merge it
