### ISSUE TITLE
Ссылка на тестовые задания C++ дает ошибку 500

### ISSUE THREAD

**Issue by sogimu** [Hexlet/ru-test-assignments#236]
https://github.com/Hexlet/ru-test-assignments?tab=readme-ov-file

![image](https://github.com/user-attachments/assets/ab83ad2b-2511-4bc1-9428-e93e143cc17f)
https://dl.funbox.ru/qt-c.pdf

**Comment by fey** [comment]
@sogimu Пришлете ПР, в нем можно удалить ссылку на это тестовое. Либо, если у кого-то есть - добаить текст задания в репо

**Comment by sayat-a** [comment]
@fey Отправил ПР

**Comment by sayat-a** [comment]
Ссылка удалена, #240

**Comment by sayat-a** [comment]
Ссылка удалена, #240
