### ISSUE TITLE
Перенести файлики и ассеты тестовых заданий в репозиторий

### ISSUE THREAD

**Issue by fey** [Hexlet/ru-test-assignments#237]
Чтобы не завязываться на свою экосистему, лучше хранить все прямо в репозитории.  У нас куча тестовых заданий для аналитиков лежат в гуглодрайве, можно их унести сюда в репозиторий. https://drive.google.com/drive/folders/1Hu_MzR8sV5k8A2MBrOZXS9QV1unoK_e9

Для больших и бинарных файлов можно использовать Git LFS https://docs.github.com/en/repositories/working-with-files/managing-large-files

**Comment by artengin** [comment]
Возьми в работу

**Comment by fey** [comment]
@artengin как успехи?

**Comment by sayat-a** [comment]
Хотел попробовать, но в процессе выяснилось что git LFS не работает с публичными форками. То есть LFS можно заливать только напрямую. Плюс у хранилища LFS лимит в 1 ГБ, а в прилагаемой директории имеется один файл с размером в 1,7 ГБ. Как-то так ¯\_(ツ)_/¯

**Comment by artengin** [comment]
У меня тоже проблема с git LFS

**Comment by artengin** [comment]
Скинул PR на пробу без git LFS, подойдет?

**Comment by fey** [comment]
Можете подсказать в каких тестовых файлах тяжелые файлы? Подумаем, что с ними делать.

**Comment by sayat-a** [comment]
Да, конечно. "ТАБАКОН Аналитик данных/TestDB.bak" - этот один файл весит 1,7 ГБ. Все остальное в совокупности тянет только на 0,4 ГБ.

**Comment by fey** [comment]
@sayat-a давайте тогда это тестовое дропнем, остальное попробуем залить с lfs

**Comment by sayat-a** [comment]
> @sayat-a давайте тогда это тестовое дропнем, остальное попробуем залить с lfs

Да, я могу попробовать, но как я говорил лимит в 1 ГБ - это один фактор. Второй фактор, LFS не поддерживает публичные форки. То есть я не могу залить через LFS на свой форкнутый репозиторий для последующего пулл-реквеста. Как вариант, это если вы в оригинальном репозитории сами создадите новую ветку для задачи, и дадите доступ туда залить

**Comment by fey** [comment]
@sayat-a давайте попробую вам доступ дать

**Comment by fey** [comment]
@sayat-a в уведомлениях должно придти приглашение в репозитоирй, сможете создать ветку тут и из нее ПР сделать в мейн.

**Comment by sayat-a** [comment]
Сделал. Отправил ПР на мерж новой ветки.

**Comment by fey** [comment]
@sayat-a чекните плз, все ли перенесено. Если да, то закрою

**Comment by sayat-a** [comment]
Да, все перенеслось

**Comment by fey** [comment]
@sayat-a можете плз чекнуть, заменили ли ссылки на эти тестовые? Я эти файлы отправил в архив, пришло письмо с запросом.
![image](https://github.com/user-attachments/assets/f689bcc8-974e-4b2f-a840-1aa901c0f7b5)
![image](https://github.com/user-attachments/assets/91a9e52a-e8a5-49f2-87b1-9fc3e223bf76)

**Comment by sayat-a** [comment]
Я заменю ссылки с гугла на репозиторий и отправлю ПР

**Comment by fey** [comment]
![image](https://github.com/user-attachments/assets/359f9f58-66c1-4a6c-9c3e-4e4857d2c08b)
еще запросики.

**Comment by sayat-a** [comment]
Отправил ПР:
Заменил в директории analytics файлы с описанием заданий в формате pdf, txt, docx на формат md
Заменил ссылки в README по аналитикам c гугл драйва на репозиторий
Удалил содержащую дубликат директорию analyst
