### ISSUE TITLE
Задание предоставлено в неполном объёме. Chatfuel — Верстальщик

### ISSUE THREAD

**Issue by arkartavtsev** [Hexlet/ru-test-assignments#37]
Отсутствуют ссылки в разделе Контент
Видео 1:
Видео 2:
Текст отзывов: https://paper.dropbox.com/doc/4DgBlRvFfFLBBWZLRF73w
Фото отзывов:
Фото раздела «О себе»:
Фото раздела «Свадебный ужин»:

Также, отсутствуют макеты, хотя, судя по тексту, подразумевается их наличие

**Comment by zbralex** [comment]
Прошу прощения, а что это?

пн, 19 нояб. 2018 г. в 15:34, Artem Kartavtsev <notifications@github.com>:

**Comment by arkartavtsev** [comment]
Это просьба дополнить тестовое задание, чтобы его можно было выполнить :)
Или вы просто предоставляете репозиторий для их публикации, но не отвечаете за само содержание, и тогда это не по адресу?

**Comment by zbralex** [comment]
по правде говоря, я впервые это вижу. И вообще, не понимаю, почему это пришло мне 😏

**Comment by zbralex** [comment]
всё , понял, я звезду поставил на всю репу. вопрос закрыт, мискузи
