### ISSUE TITLE
Тестовое задание от SoftPro расположено в приватном Google хранилище

### ISSUE THREAD

**Issue by StepanenkoArtem** [Hexlet/ru-test-assignments#64]
Задание от SoftPro расположено в Google Drive с ограниченным доступом. Для доступа к заданию необходимо запрашивать доступ.
https://drive.google.com/drive/folders/151UdoZGZZtdv5-KP_51yx3CzT1kgIBQn

**Comment by AABur** [comment]
действительно Fixed можно закрывать
