### ISSUE TITLE
Maths

### ISSUE THREAD

**Issue by Vbhutani191** [Hexlet/ru-test-assignments#95]

**Comment by ashikov** [comment]
@Vbhutani191, скажите, пожалуйста, вы создали issue по ошибке или просто забыли заполнить описание? Если есть какие-то предложения, то смело пишите в комменты. Если же нет, то я закрою этот топик.

**Comment by Singrana3193** [comment]
Оу, создано по ошибке, сорян

ср, 13 квіт. 2022 р. о 14:15 Roman Ashikov ***@***.***> пише:

**Comment by ashikov** [comment]
Ничего страшного! Issue закрываю.
